name: GUICommands
version: 1.3.1
author: JohZant
main: com.arch.guicommands.GUICommands
website: www.archetype-mc.com
softdepend: [PlaceholderAPI]
commands:
  guicommands:
      description: 'Core Command for GUICommands'
      usage: '/guicommands'
permissions:
   guicommands.*:
     description: Gives access to all GUICommands commands
     default: op
     children:
       guicommands.admin: true
   guicommands.admin:
     description: Gives access to administrative command subsection
     default: op
     children:
       guicommands.admin.reload: true